---
galaxy_info:
  author: martins
  description: Common Kubernetes node preparation for all cluster nodes
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: Ubuntu
      versions:
        - focal
        - jammy

dependencies: []
