apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudflared
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@gitlab.com:mudris-dev/devops/homelab-platform.git
    targetRevision: HEAD
    path: k8s/apps/cloudflared
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true